version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - 8888:8888
    volumes:
      - ./:/usr/src/logistics_now_challenge:ro
    depends_on:
      - db
    command: uvicorn solution_2:api --host 0.0.0.0 --port 8888 --reload
    env_file:
      - ./.env
  
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: